### ISSUE TITLE
Desduplicação de eventos

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-fb-conversions#3]
Nos eventos de compra que são os únicos utilizados hoje, estão ocorrendo duplicação de informação, logo o facebook sugere isso aqui https://www.facebook.com/business/help/823677331451951?id=1205376682832142 para evitar que tenha duplicação de informação de compra

**Comment by leomp12** [comment]
Não é por causa do pixel na loja? Você tem certeza que o evento é criado em duplicade via ocnversion api? Porque acho que o Webhook não chegaria repetido aqui não..
Me manda um ID de pedido que apareceu duplicado por favor

**Comment by matheusgnreis** [comment]
Ele é duplicado por causa do pixel, pois o pixel envia também. Então o facebook sugere que em evento de compra, precisa realizar essa desduplicação com event_id. O wesley informou que enviaram isso pra ele, falando que esse envio duplo sem event_id, irá gerar duplicação e ai trazer problema pra ele.

**Comment by leomp12** [comment]
Então não é issue daqui, e no CMS já tem uma opção pra desativar os eventos `Purchase` nas configurações do pixel.

**Comment by leomp12** [comment]
Assim que esse app foi publicado a opção foi adicionada na configuração do widget no CMS, eu acredito que resolva.

**Comment by matheusgnreis** [comment]
Deve resolver mesmo, porque ai entra só um evento
